=== mryzleitsev/mezduslovjansky-jezyk/XML/index.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT index (mainInfo, content)>
        <!ELEMENT mainInfo (author, links, countriesLn, imgs, linguists)>
        <!ELEMENT author (name, surname)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT links (link+)>
        <!ELEMENT link (#PCDATA)>
        <!ATTLIST link
                theme (mainPage | communityPage | grammarPage | contactPage | myPage | pg) #REQUIRED>
        <!ELEMENT countriesLn (countryLn+)>
        <!ELEMENT countryLn (#PCDATA)>
        <!ELEMENT imgs (img+)>
        <!ELEMENT img (#PCDATA)>
        <!ATTLIST img source CDATA #REQUIRED>
        <!ELEMENT linguists (linguist+)>
        <!ELEMENT linguist (#PCDATA)>
        <!ELEMENT content (paragraphs)>
        <!ELEMENT paragraphs (goal, idea, background, history, earlyProj, TwthCentury)>
        <!ELEMENT goal (#PCDATA)>
        <!ELEMENT idea (#PCDATA)>
        <!ELEMENT background (#PCDATA)>
        <!ELEMENT history (#PCDATA)>
        <!ELEMENT earlyProj (#PCDATA)>
        <!ELEMENT TwthCentury (#PCDATA)>

=== mryzleitsev/mezduslovjansky-jezyk/XML/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index SYSTEM "index.dtd">

<index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd">
        <mainInfo>
            <author>
                <name>Myron</name>
                <surname>Ryzleitsev</surname>
            </author>
            <links>
                <link theme="mainPage">./index.html</link>
                <link theme="grammarPage">./grammar.html</link>
                <link theme="communityPage">./community.html</link>
                <link theme="contactPage">./contact.html</link>
                <link theme="myPage">https://mryzleitsev.space/</link>
                <link theme="pg">https://pg.edu.pl/</link>
            </links>
            <countriesLn>
                <countryLn>Ukrainian</countryLn>
                <countryLn>Russian</countryLn>
                <countryLn>Belarusian</countryLn>
                <countryLn>Polish</countryLn>
                <countryLn>Slovak</countryLn>
                <countryLn>Slovenian</countryLn>
                <countryLn>Czech</countryLn>
                <countryLn>Serbian</countryLn>
                <countryLn>Macedonian</countryLn>
                <countryLn>Bulgarian</countryLn>
            </countriesLn>
            <imgs>
                <img source="res/flags/ua.svg">Ukrainian</img>
                <img source="res/flags/ru.svg">Russian</img>
                <img source="res/flags/by.svg">Belarusian</img>
                <img source="res/flags/pl.svg">Polish</img>
                <img source="res/flags/sk.svg">Slovak</img>
                <img source="res/flags/si.svg">Slovenian</img>
                <img source="res/flags/cz.svg">Czech</img>
                <img source="res/flags/rs.svg">Serbian</img>
                <img source="res/flags/mk.svg">Macedonian</img>
                <img source="res/flags/bg.svg">Bulgarian</img>
            </imgs>
            <linguists>
                <linguist>Grigor Parlichev (1830–1893)</linguist>
                <linguist>Matija Ban (1818–1903)</linguist>
                <linguist>Radoslav Razlag</linguist>
                <linguist>Božidar Raič</linguist>
            </linguists>
        </mainInfo>
    <content>
        <paragraphs>
            <goal>
                One of my interests is the study of languages, especially Slavic ones. There is an interesting artificial language that allows all Slavs to understand each other, somewhat similar to Esperanto, created by a Polish linguist. However, this language is based on Old Slavic with the addition of many modern words and simplified forms. This language became the basis for a project on hypertext and hypermedia.

                So, what is the Interslavic language more scientifically? It is an auxiliary pan-Slavic language based on the linguistic material of Old Slavic and living Slavic languages, designed for communication among their speakers. It enables communication without using individual Slavic national languages.
                Interslavic can be classified as a naturalistic artificial language. Essentially, it is a modern functional continuation of Old Slavic, aimed at mutual understanding without the need for speakers to learn each other's specific Slavic languages. The grammar and vocabulary are based on common structures in Slavic languages, with simplified grammar and minimal exceptions, making it easy for Slavic speakers to learn. It is primarily created to help travelers and people communicate both in person and online without the need for translation into multiple languages, allowing individuals to speak and write clearly for speakers of almost any living Slavic language and better understand texts in other Slavic languages.

                Unlike Slovio, Interslavic does not claim independence. It is not intended for full-fledged communication but rather for pan-Slavic communication. For example, a document written in Interslavic does not need to be translated into all Slavic languages. Interslavic can be written using both the Latin and Cyrillic alphabets.
            </goal>
            <idea>
                Slavic languages are a relatively homogeneous group with three subgroups that have very similar structures and many common features in grammar, vocabulary, and syntax. Knowing one Slavic language is usually sufficient to at least partially understand speech in another Slavic language.

                The main goal of the developers of Interslavic was to create a language that would be understood without prior study by all or most speakers of Slavic languages. The grammar and vocabulary are entirely based on common features of Slavic language grammars, with about 80% similarity to Russian grammar. The vocabulary is created through careful selection of words from existing Slavic languages to be understandable to all or most speakers of Slavic languages.

                The language has a philosophy similar to Interlingua, which serves as a similar unifying language for Romance languages and serves as an example for the formation of Interslavic. The goal of the so-called zonal language is to use it for communication within a specific group, all members of which have passive understanding of the language without the need to study it. Unlike established universal international auxiliary languages like Esperanto, zonal languages often have a complex internal structure. On the other hand, the grammar and morphology of Interslavic contain very few exceptions, making it easy to learn.

                The project is not political and does not intend to replace existing Slavic languages. It will be used as a computer language to facilitate pan-Slavic communication. The proposed language would also improve the quality of machine translation.
            </idea>
            <background>
                The history of the Interslavic or Pan-Slavic language is closely tied to the ideals of Pan-Slavic ideology, rooted in the belief in the necessity of Slavic national political unity based on ethnic, cultural, and linguistic commonality. These ideas have led to the need for a unified Slavic language.

                For a long time, Russian was considered the primary candidate for the role of the common language of the Slavic peoples, being the largest in terms of geographical area and number of speakers. Throughout the 19th century, it was the de facto Slavic language used at the level of the main state language, being the native language for over half of the Slavic population in Europe. This future for the Russian language not only gained popularity among Russian-speaking Slavs but was also the main viewpoint of contemporary Pan-Slavists, such as Ludovit Stur.

                Others, however, believed that Church Slavonic would be a much better and politically neutral solution for creating a common language. Church Slavonic, in previous centuries, held weight as a regional language and is still used during Slavic Orthodox liturgy, occupying a position in the Orthodox Church similar to Latin in the Catholic Church. Church Slavonic also has greater linguistic proximity to the common ancestor of all Slavic languages – Proto-Slavic. However, it has some drawbacks, including outdated Cyrillic script, highly complex grammar, and a vocabulary with many obsolete and poorly understood words by modern Slavs. Thus, early Pan-Slavic projects aimed at modernizing and using the outdated Church Slavonic language for everyday needs.
            </background>
            <history>
                The Interslavic language has a long history of development, predating by centuries even major artificial languages like Volapük and Esperanto. The earliest known attempt to create the first Interslavic language, which was successful, dates back to 1659–1666 and was undertaken by the Croatian priest Juraj Križanić. In its modern form, Interslavic emerged in 2006 under the name "Slavjanski." In 2011, a reform and merger with two other projects occurred, after which the language was renamed "Interslavic," a term first mentioned by Czech linguist Ignác Hošek in 1908.
            </history>
            <earlyProj>
                In 1583, Croatian priest Sime Budinić translated Peter Canisius's catechism, "Summa Doctrinae Christianae," into a language he created. The translation was released in both Latin and Cyrillic scripts, using rules he devised based on the Ikavian-Chakavian dialect. Budinić's language proved to be mutually intelligible for all South Slavic peoples of that time.

                In 1661, Yuriy Križanić, a Croatian theologian, philosopher, writer, linguist, historian, ethnographer, publicist, and encyclopedist living in Moscow, was accused of supporting the Uniates and sent into exile in Tobolsk, where he spent 16 years. In Tobolsk, Križanić wrote his major works, including "Politics," "On Divine Providence," "Interpretation of Historical Prophecies," "On Holy Baptism," and "Grammatical Inquiry into the Russian Language (the idea of a pan-Slavic language)," where he described and developed the idea of creating an Interslavic language. This idea was first outlined by him in 1665 in the literary work "Gramatíčno izkâzanje ob rúskom jezíku," published in Russian as "Грамматическое изыскание о русском языке (идея всеславянского языка)," where he proposed, for convenience, to replace the names of letters (az, buki, vedi, etc.) with monosyllabic ones, essentially anticipating the reform of the Russian orthography by 260 years.
